strictness: veryhigh
max-line-length: 110

pylint:
  disable:
    - wrong-import-order
    - too-many-arguments
    - too-many-branches
    - too-many-locals
    - too-many-statements
    - too-many-nested-blocks
    - too-many-lines
    - too-few-public-methods
    - line-too-long # done by Black

pep8:
  options:
    max-line-length: 110
  disable:
    - E203 # whitespace before ':'
    - E501 # line too long, Done by Black

mypy:
  run: true

mccabe:
  run: false
