strictness: veryhigh
max-line-length: 110
doc-warnings: true

pylint:
  disable:
    - wrong-import-order
    - too-many-arguments
    - too-many-branches
    - too-many-locals
    - too-many-statements
    - too-many-nested-blocks
    - too-many-lines
    - too-few-public-methods
    - line-too-long # done by Black

pep8:
  options:
    max-line-length: 110
  disable:
    - E203 # whitespace before ':'
    - E501 # line too long, Done by Black

pep257:
  disable:
    - D212 # Multi-line docstring summary should start at the first line
    - D407 # Missing dashed underline after section
    - D413 # Missing blank line after last section
    - D200 # One-line docstring should fit on one line with quotes
    - D203 # 1 blank line required before class
    - D202 # No blank lines allowed after function docstring

mypy:
  run: true

mccabe:
  run: false
