# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/master/c2cciutils/schema.json

version:
  branch_to_version_re:
    - from: ([0-9]+.[0-9]+)
      to: \1
    - from: master
      to: '1.2'

checks:
  versions:
    extra_versions:
      - '1.2'

publish:
  pypi:
    packages:
      - path: .
    versions:
      - version_tag
      - version_branch
      - rebuild
