version:
  branch_to_version_re:
    - from: ([0-9]+.[0-9]+)
      to: \1
    - from: master
      to: '1.1'

checks:
  versions:
    extra_versions:
      - '1.1'

audit:
  pipenv:
    python_versions:
      - 3.6.12

publish:
  pypi:
    packages:
    - path: .
    - path: test/pkg
      versions: []
    versions:
      - version_tag
      - version_branch
