# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/master/c2cciutils/schema.json

checks:
  codespell:
    ignore_re:
      - ^test/Pipfile\.lock$
      - ^(.*/)?poetry\.lock$

audit:
  snyk:
    files_no_install:
      - example-project/ci/requirements.txt

publish:
  pypi:
    versions:
      - version_tag
      - version_branch
      - rebuild
