---
name: Audit

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  audit:
    name: Audit
    uses: camptocamp/c2cciutils/.github/workflows/reusable-audit.yaml@master
    with:
      branches: "['master', '1.1']"
    secrets:
      CI_GPG_PRIVATE_KEY: ${{ secrets.CI_GPG_PRIVATE_KEY }}
      GOPASS_CI_GITHUB_TOKEN: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}
