---
name: Continuous integration

on:
  push:

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: pypi docker

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --editable=.

      - name: Checks
        run: c2cciutils-checks

      - name: Build
        run: make
      - name: Build example
        run: (cd example-project/; make)

      - run: sudo chmod go+rw -R *.egg-info
      - name: Publish
        run: c2cciutils-publish

  audit:
    runs-on: ubuntu-20.04
    name: Audit
    timeout-minutes: 10
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: asdf-vm/actions/install@v1
        with:
          tool_versions: python 3.8.0

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --editable=.

      - name: Audit
        run: c2cciutils-audit --branch=master
        env:
          GITHUB_TOKEN: ${{ github.token }}
