---
name: Continuous integration

on:
  pull_request:
    paths-ignore:
      - 'example-project/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'example-project/**'

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 10
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - run: |
          for package in $(python3 -m pip list --outdated --format=freeze | cut -d = -f 1)
          do
              echo ::group::Upgrade $package
              sudo python3 -m pip install --upgrade $package || true
              echo ::endgroup::
          done

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: pypi docker
        if: env.HAS_SECRETS == 'HAS_SECRETS'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: cd c2cciutils; npm install
      - run: python3 ./setup.py egg_info --no-date bdist_wheel
      - run: python3 -m pip install --user --force-reinstall dist/*.whl
      - run: rm -rf dist build

      - name: Checks
        run: c2cciutils-checks

      - name: Build
        run: make
      - name: Build example
        run: (cd example-project/; make)

      - run: sudo chmod go+rw -R *.egg-info
      - name: Publish
        run: c2cciutils-publish
        if: env.HAS_SECRETS == 'HAS_SECRETS'

  k8s:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - run: |
          for package in $(python3 -m pip list --outdated --format=freeze | cut -d = -f 1)
          do
              echo ::group::Upgrade $package
              sudo python3 -m pip install --upgrade $package || true
              echo ::endgroup::
          done

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: cd c2cciutils; npm install
      - run: python3 ./setup.py egg_info --no-date bdist_wheel
      - run: python3 -m pip install --user --force-reinstall dist/*.whl
      - run: rm -rf dist build

      - name: Install
        run: c2cciutils-k8s-install
      - name: Checks
        run: c2cciutils-checks

      - name: Create DB
        run: c2cciutils-k8s-db --script=test/init.sql

      - run: kubectl run test-pod --restart=Never --namespace=default --image=busybox --command -- tail -f /dev/null

      - name: Wait
        run: c2cciutils-k8s-wait
      - name: Logs
        run: c2cciutils-k8s-logs
        if: always()

      - name: Clean the database
        run: c2cciutils-k8s-db --cleanup
        if: always()

  audit:
    uses: ./.github/workflows/reusable-audit.yaml
    with:
      branches: "['master', '1.1']"
    secrets:
      CI_GPG_PRIVATE_KEY: ${{ secrets.CI_GPG_PRIVATE_KEY }}
      GOPASS_CI_GITHUB_TOKEN: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}
