---
name: Rebuild

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  rebuild:
    runs-on: ubuntu-20.04
    name: Rebuild
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '1.0'
          - master

    steps:
      - run: |
          for package in $(python3 -m pip list --outdated --format=freeze | cut -d = -f 1)
          do
              echo ::group::Upgrade $package
              sudo python3 -m pip install --upgrade $package || true
              echo ::endgroup::
          done

      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: pypi docker

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --editable=.

      - name: Checks
        run: c2cciutils-checks

      - name: Build
        run: make

      - run: sudo chmod go+rw -R *.egg-info
      - name: Publish
        run: c2cciutils-publish --type=rebuild --branch=${{ matrix.branch }}
