---
name: Audit

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: string
    secrets:
      CI_GPG_PRIVATE_KEY:
        required: true
      GOPASS_CI_GITHUB_TOKEN:
        required: true

jobs:
  audit:
    runs-on: ubuntu-20.04
    name: Audit
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(inputs.branches) }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          github-gopass-ci-token: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user wheel
      - run: python3 ./setup.py egg_info --no-date bdist_wheel
      - run: python3 -m pip install --user --force-reinstall dist/*.whl

      - name: Audit
        run: c2cciutils-audit
        env:
          GITHUB_TOKEN: ${{ github.token }}
